# Generated by Django 5.2.10 on 2026-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0002_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
