# Generated by Django 5.2.10 on 2026-03-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0003_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
