# Generated by Django 5.2.10 on 2026-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_user_study_end_user_study_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='difficulty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='importance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='num_sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='recommended_session_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_days_before_due',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='urgency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
